name: Find most frequently modified functions
author: Sarah Nadi
description: Display the most frequently modified functions, which can provide insights to prioritize testing and refactoring efforts.

branding:
  icon: info
  color: yellow

inputs:
  topn:
    description: "The number of top frequently modified functions to return"
    type: number
    default: 10

runs:
  using: "composite"
  steps:
    - name: Checkout out code
      uses: actions/checkout@v3

    - name: Set up Python
    - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
    
    - name: Install dependencies
    - run: |
        pip install -r requirements.txt

    - name: Find frequently modified functions
      run: python get_freq_modified_fns.py --path . --topn ${{ inputs.topn }} >> $GITHUB_STEP_SUMMARY