name: Find most frequently modified functions

on:
  workflow_dispatch:
    inputs:
      topn:
        description: "The number of top frequently modified functions to return"
        type: number
        default: 10
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      topn: "${{ github.event.inputs.topn }}"
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - run: |
          pip install -r requirements.txt

  frequency_analysis:
    needs:
      - setup
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:      
      - name: Checkout github repo
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Find frequently modified functions
        run: |
          curr_dir=`pwd`
          python get_freq_modified_fns.py \
            --path $curr_dir \
            --topn ${{ needs.setup.outputs.topn }} 